// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMe3Ed7qHCwkSQklgb5mC2A0-Zkt7xnPE',
    appId: '1:66862164693:web:8228ea72d71f15b99b505c',
    messagingSenderId: '66862164693',
    projectId: 'hichat-1292b',
    authDomain: 'hichat-1292b.firebaseapp.com',
    storageBucket: 'hichat-1292b.firebasestorage.app',
    measurementId: 'G-CEE9QET9FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVW31b0VkmxfSF4jiQcjTjB9rSpF6sV8E',
    appId: '1:66862164693:android:ddf6b0a3c85a39449b505c',
    messagingSenderId: '66862164693',
    projectId: 'hichat-1292b',
    storageBucket: 'hichat-1292b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANNsiqiJ9dlfWx3DlSmY1zOTRhOELLsjQ',
    appId: '1:66862164693:ios:7149976dc79b96249b505c',
    messagingSenderId: '66862164693',
    projectId: 'hichat-1292b',
    storageBucket: 'hichat-1292b.firebasestorage.app',
    iosBundleId: 'com.example.hichat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANNsiqiJ9dlfWx3DlSmY1zOTRhOELLsjQ',
    appId: '1:66862164693:ios:7149976dc79b96249b505c',
    messagingSenderId: '66862164693',
    projectId: 'hichat-1292b',
    storageBucket: 'hichat-1292b.firebasestorage.app',
    iosBundleId: 'com.example.hichat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMe3Ed7qHCwkSQklgb5mC2A0-Zkt7xnPE',
    appId: '1:66862164693:web:e63ce13211a717109b505c',
    messagingSenderId: '66862164693',
    projectId: 'hichat-1292b',
    authDomain: 'hichat-1292b.firebaseapp.com',
    storageBucket: 'hichat-1292b.firebasestorage.app',
    measurementId: 'G-Q419PEZ91X',
  );
}
